version: '3'

services:
  db:
    image: postgres:14
    container_name: blog_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    
  backend:
    container_name: blog_backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    build: .

  redis:
    container_name: blog_redis
    ports:
      - "6379:6379"
    volumes:
        - ./redis_data:/data
    image: redis
    
  celery:
    build: .
    command: celery -A config worker --beat -l info
    volumes:
      - ./backend/:/backend
    env_file: .env
    depends_on:
      - redis