version: '3'

services:
  db:
    image: postgres:14
    container_name: blog_db
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  backend:
    container_name: blog_backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    build: .